apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/fluxcd/flux2/manifests//monitoring/grafana?ref=main
  - gateway.yaml
  - flagger.yaml
  - prometheus.yaml
patchesStrategicMerge:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: grafana-datasources
      namespace: flux-system
    data:
      datasources.yaml: |-
        apiVersion: 1
        deleteDatasources:
          - name: prometheus
        datasources:
        - name: prometheus
          type: prometheus
          access: proxy
          url: http://appmesh-prometheus.appmesh-system:9090
          isDefault: true
          editable: true
          version: 1
