apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-addons
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cluster-addons
  prune: true
  validation: client
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: appmesh-controller-webhook-service
      namespace: appmesh-system
    - apiVersion: apps/v1
      kind: Deployment
      name: appmesh-controller
      namespace: appmesh-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mesh
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: cluster-addons
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/mesh
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mesh-addons
  namespace: flux-system
spec:
  interval: 30m
  timeout: 1m
  dependsOn:
    - name: mesh
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/mesh-addons
  prune: true
  validation: client
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: appmesh-gateway
      namespace: appmesh-gateway
    - apiVersion: apps/v1
      kind: Deployment
      name: appmesh-gateway
      namespace: appmesh-gateway
