apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - namespace.yaml
  - loadtester
  - podinfo
vars:
  - name: NAMESPACE
    objref:
      kind: Namespace
      name: apps
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
configurations:
  - kustomizeconfig.yaml

